export const NEWS_FETCH_ALL="NEWS_FETCH_ALL";

export const POST_FETCH="POST_FETCH";
export const POST_FETCH_ALL="NEWS_FETCH_ALL";
export const POST_FETCH_SUCCEEDED="POST_FETCH_SUCCEEDED";
export const POST_FETCH_FAILED="POST_FETCH_FAILED";
export const POST_BLANK="POST_BLANK";


